name: Summarize Errors
on:
  workflow_run:
    workflows: [Review Workflow]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write
  actions: read
  id-token: write

jobs:
  summarize:
    runs-on:
      group: arc-prod-blue
    steps:
    - uses: intel-innersource/frameworks.actions.gnai.summarize-errors@main
