name: Test Workflow

on:
  push:
    branches: [ "test" ]

  pull_request:
    branches: [ "test" ]

  permissions:
    contents: read
    pull-requests: write
    id-token: write

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v6

    - name: config
      run: make defconfig

    - name: make
      run: make

    - uses: intel-innersource/frameworks.actions.gnai.agentic-code-review@v1

