name: Test Workflow

on:
  pull_request:
    branches:
    - main
    - linus
    - test

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v6

    - name: config
      run: make defconfig

    - name: make
      run: make

    - uses: intel-innersource/frameworks.actions.gnai.agentic-code-review@v1

